import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/ui/header'
import Footer from '@/components/ui/footer'
import clsx from 'clsx'
import { noto, mono } from '@/app/fonts'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="ja">
            <body
                className={clsx(
                    'flex flex-col min-h-screen',
                    noto.variable,
                    mono.variable
                )}
            >
                <Header />
                <main className="grow">{children}</main>
                <Footer />
            </body>
        </html>
    )
}
